"""
Groq API client service.

This module contains an async client responsible for sending
streaming chat completion requests to Groq's OpenAI-compatible API
and yielding partial text responses as they arrive.
"""

import json
from typing import AsyncIterator

import httpx

from app.core.config import settings


class GroqStreamError(Exception):
    """
    Raised when an error occurs while streaming from the Groq API.
    """
    pass


class GroqClient:
    """
    Async client for interacting with the Groq LLM API.

    This client is designed specifically for streaming chat
    completions and yields text chunks incrementally.
    """

    def __init__(self) -> None:
        self._base_url: str = settings.groq_base_url
        self._api_key: str = settings.groq_api_key

    async def stream_chat_completion(
        self,
        messages: list[dict[str, str]],
        model: str | None = None,
    ) -> AsyncIterator[str]:
        """
        Stream chat completion output from Groq.

        Args:
            messages: List of chat messages in OpenAI-compatible format.
            model: Optional model override. If not provided,
                   the default model from settings is used.

        Yields:
            str: Partial text chunks generated by the LLM.
        """

        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }

        payload = {
            "model": model or settings.groq_default_model,
            "messages": messages,
            "stream": True,
        }

        try:
            async with httpx.AsyncClient(
                base_url=self._base_url,
                timeout=None,
            ) as client:
                async with client.stream(
                    method="POST",
                    url="/chat/completions",
                    headers=headers,
                    json=payload,
                ) as response:
                    response.raise_for_status()

                    async for line in response.aiter_lines():
                        if not line:
                            continue

                        if line.strip() == "data: [DONE]":
                            break

                        if line.startswith("data: "):
                            data = json.loads(line.removeprefix("data: "))

                            delta = data["choices"][0]["delta"]
                            content = delta.get("content")

                            if content:
                                yield content

        except httpx.HTTPError as e:
          
            raise GroqStreamError("Groq API request failed") from e

        except json.JSONDecodeError as e:
         
            raise GroqStreamError("Failed to parse Groq streaming response") from e

        except Exception as e:

            raise GroqStreamError("Unexpected error during Groq streaming") from e
