"""
Groq API client service.

This module contains an async client responsible for sending
streaming chat completion requests to Groq's OpenAI-compatible API
and yielding partial text responses as they arrive.
"""

import json
from typing import AsyncIterator
import httpx
import structlog
from app.core.config import settings


logger = structlog.get_logger()

class GroqStreamError(Exception):
    """
    Raised when an error occurs while streaming from the Groq API.
    """
    pass


class GroqClient:
    """
    Async client for interacting with the Groq LLM API.

    This client is designed specifically for streaming chat
    completions and yields text chunks incrementally.
    """

    def __init__(self) -> None:
        self._base_url: str = settings.groq_base_url
        self._api_key: str = settings.groq_api_key

    async def stream_chat_completion(
        self,
        messages: list[dict[str, str]],
        model: str | None = None,
    ) -> AsyncIterator[str]:
        """
        Stream chat completion output from Groq.

        Args:
            messages: List of chat messages in OpenAI-compatible format.
            model: Optional model override. If not provided,
                   the default model from settings is used.

        Yields:
            str: Partial text chunks generated by the LLM.
        """
        
        log = logger.bind(model=model or settings.groq_default_model)

        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }

        payload = {
            "model": model or settings.groq_default_model,
            "messages": messages,
            "stream": True,
        }

        try:
            async with httpx.AsyncClient(
                base_url=self._base_url,
                timeout=None,
            ) as client:
                async with client.stream(
                    method="POST",
                    url="/chat/completions",
                    headers=headers,
                    json=payload,
                ) as response:
                   
                    if response.is_error:
                        await response.aread()
                        log.error("groq_api_http_error", status_code=response.status_code, response_body=response.text)
                        raise GroqStreamError(f"Groq API error: {response.status_code}")

                    async for line in response.aiter_lines():
                        if not line:
                            continue

                        if line.strip() == "data: [DONE]":
                            break

                        if line.startswith("data: "):
                            data = json.loads(line.removeprefix("data: "))

                            delta = data["choices"][0]["delta"]
                            content = delta.get("content")

                            if content:
                                yield content

        except GroqStreamError:
            raise

        except httpx.HTTPError as e:
            log.error("groq_network_error", error=str(e))
            raise GroqStreamError("Groq API connection failed") from e

        except json.JSONDecodeError as e:
            log.error("groq_json_decode_error", error=str(e), exc_info=True)
            raise GroqStreamError("Failed to parse Groq response") from e

        except Exception as e:
            log.error("groq_unexpected_error", error=str(e), exc_info=True)
            raise GroqStreamError("An unexpected error occurred") from e