"""add chat evaluations table

Revision ID: 87305e11a64c
Revises: 66af22511718
Create Date: 2026-01-26 10:45:21.276351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87305e11a64c'
down_revision: Union[str, Sequence[str], None] = '66af22511718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_log_id', sa.Integer(), nullable=False),
    sa.Column('judge_model_name', sa.String(length=100), nullable=False),
    sa.Column('rubric_version', sa.String(length=50), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Integer(), nullable=False),
    sa.Column('clarity', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_log_id'], ['chat_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_log_id', 'rubric_version', name='uq_chat_eval_log_rubric')
    )
    op.create_index(op.f('ix_chat_evaluations_chat_log_id'), 'chat_evaluations', ['chat_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_evaluations_chat_log_id'), table_name='chat_evaluations')
    op.drop_table('chat_evaluations')
    # ### end Alembic commands ###
